import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi'
import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'

export default defineNuxtPlugin((nuxtApp) => {
  const savedTheme = import.meta.client ? (localStorage.getItem('ha-theme') ?? 'dark') : 'dark'

  const vuetify = createVuetify({
    icons: {
      defaultSet: 'mdi',
      aliases,
      sets: { mdi },
    },
    theme: {
      defaultTheme: savedTheme,
      themes: {
        dark: {
          dark: true,
          colors: {
            background: '#0f172a',
            surface: '#1e293b',
            'surface-variant': '#334155',
            'surface-bright': '#273548',
            primary: '#6366f1',
            'primary-darken-1': '#4f46e5',
            secondary: '#64748b',
            error: '#ef4444',
            success: '#22c55e',
            warning: '#f59e0b',
            info: '#3b82f6',
            'on-background': '#f1f5f9',
            'on-surface': '#f1f5f9',
          },
        },
        light: {
          dark: false,
          colors: {
            background: '#f8fafc',
            surface: '#ffffff',
            'surface-variant': '#f1f5f9',
            'surface-bright': '#ffffff',
            primary: '#4f46e5',
            'primary-darken-1': '#3730a3',
            secondary: '#64748b',
            error: '#dc2626',
            success: '#16a34a',
            warning: '#d97706',
            info: '#2563eb',
          },
        },
        dracula: {
          dark: true,
          colors: {
            background: '#282a36',
            surface: '#44475a',
            'surface-variant': '#6272a4',
            'surface-bright': '#383a59',
            primary: '#bd93f9',
            'primary-darken-1': '#a975f7',
            secondary: '#6272a4',
            error: '#ff5555',
            success: '#50fa7b',
            warning: '#ffb86c',
            info: '#8be9fd',
            'on-background': '#f8f8f2',
            'on-surface': '#f8f8f2',
          },
        },
        nord: {
          dark: true,
          colors: {
            background: '#2e3440',
            surface: '#3b4252',
            'surface-variant': '#434c5e',
            'surface-bright': '#3d4760',
            primary: '#88c0d0',
            'primary-darken-1': '#5e81ac',
            secondary: '#4c566a',
            error: '#bf616a',
            success: '#a3be8c',
            warning: '#ebcb8b',
            info: '#81a1c1',
            'on-background': '#eceff4',
            'on-surface': '#eceff4',
          },
        },
        catppuccin: {
          dark: true,
          colors: {
            background: '#1e1e2e',
            surface: '#313244',
            'surface-variant': '#45475a',
            'surface-bright': '#2a2a3d',
            primary: '#cba6f7',
            'primary-darken-1': '#b4befe',
            secondary: '#585b70',
            error: '#f38ba8',
            success: '#a6e3a1',
            warning: '#fab387',
            info: '#89b4fa',
            'on-background': '#cdd6f4',
            'on-surface': '#cdd6f4',
          },
        },
        lumon: {
          dark: true,
          colors: {
            background: '#0d1b2a',
            surface: '#1b2838',
            'surface-variant': '#243447',
            'surface-bright': '#1e2f44',
            primary: '#4d9de0',
            'primary-darken-1': '#2e7ec7',
            secondary: '#718fa8',
            error: '#e05c5c',
            success: '#4caf7d',
            warning: '#e0a040',
            info: '#4d9de0',
            'on-background': '#dce8f5',
            'on-surface': '#dce8f5',
          },
        },
        retro82: {
          dark: true,
          colors: {
            background: '#1a0e02',
            surface: '#2a1a06',
            'surface-variant': '#3d2810',
            'surface-bright': '#2f1e08',
            primary: '#ff8c00',
            'primary-darken-1': '#cc6e00',
            secondary: '#b86500',
            error: '#ff4444',
            success: '#77cc44',
            warning: '#ffcc00',
            info: '#44aaff',
            'on-background': '#f5e0c0',
            'on-surface': '#f5e0c0',
          },
        },
        miasma: {
          dark: true,
          colors: {
            background: '#222222',
            surface: '#2e2e2e',
            'surface-variant': '#3a3a3a',
            'surface-bright': '#333333',
            primary: '#7d9a8a',
            'primary-darken-1': '#5f7a6a',
            secondary: '#6a7a72',
            error: '#cc5555',
            success: '#5a8a5a',
            warning: '#b89060',
            info: '#5a7a9a',
            'on-background': '#d4d4d4',
            'on-surface': '#d4d4d4',
          },
        },
        neongreen: {
          dark: true,
          colors: {
            background: '#090909',
            surface: '#111111',
            'surface-variant': '#1a1a1a',
            'surface-bright': '#141414',
            primary: '#39ff14',
            'primary-darken-1': '#2acc0f',
            secondary: '#00ff88',
            error: '#ff2244',
            success: '#39ff14',
            warning: '#ffcc00',
            info: '#00aaff',
            'on-background': '#e0ffe0',
            'on-surface': '#e0ffe0',
          },
        },
        jarvis: {
          dark: true,
          colors: {
            background: '#0a0c12',
            surface: '#141820',
            'surface-variant': '#1e2430',
            'surface-bright': '#181c28',
            primary: '#e63946',
            'primary-darken-1': '#c1121f',
            secondary: '#ffd700',
            error: '#e63946',
            success: '#4caf50',
            warning: '#ffd700',
            info: '#0096ff',
            'on-background': '#e8eaf0',
            'on-surface': '#e8eaf0',
          },
        },
        anime: {
          dark: true,
          colors: {
            background: '#0d0d14',
            surface: '#1a1a26',
            'surface-variant': '#252538',
            'surface-bright': '#1f1f32',
            primary: '#e91e8c',
            'primary-darken-1': '#c0156f',
            secondary: '#ff6b35',
            error: '#ff4444',
            success: '#39ff14',
            warning: '#ffaa00',
            info: '#00aaff',
            'on-background': '#f0e0f5',
            'on-surface': '#f0e0f5',
          },
        },
        gruvboxmat: {
          dark: true,
          colors: {
            background: '#1d2021',
            surface: '#282828',
            'surface-variant': '#32302f',
            'surface-bright': '#2c2b28',
            primary: '#a9b665',
            'primary-darken-1': '#89966a',
            secondary: '#928374',
            error: '#ea6962',
            success: '#a9b665',
            warning: '#d8a657',
            info: '#7daea3',
            'on-background': '#d4be98',
            'on-surface': '#d4be98',
          },
        },
        aethernight: {
          dark: true,
          colors: {
            background: '#0e0e10',
            surface: '#1a1a1e',
            'surface-variant': '#252529',
            'surface-bright': '#1e1e22',
            primary: '#7c83e5',
            'primary-darken-1': '#5e66cc',
            secondary: '#a77bca',
            error: '#e56b73',
            success: '#78c886',
            warning: '#e5a050',
            info: '#5bbfe5',
            'on-background': '#d8d8ee',
            'on-surface': '#d8d8ee',
          },
        },
        auradark: {
          dark: true,
          colors: {
            background: '#15141b',
            surface: '#1c1b22',
            'surface-variant': '#2a2839',
            'surface-bright': '#201e2b',
            primary: '#a277ff',
            'primary-darken-1': '#8c5fe0',
            secondary: '#f694ff',
            error: '#f05a7e',
            success: '#61ffca',
            warning: '#ffca85',
            info: '#82e2ff',
            'on-background': '#edecee',
            'on-surface': '#edecee',
          },
        },
        anthropic: {
          dark: true,
          colors: {
            background: '#19191c',
            surface: '#222226',
            'surface-variant': '#2d2d33',
            'surface-bright': '#262629',
            primary: '#e8612c',
            'primary-darken-1': '#c74e21',
            secondary: '#888895',
            error: '#e05252',
            success: '#5ab88a',
            warning: '#e89c3c',
            info: '#5a9ee0',
            'on-background': '#e8e8ec',
            'on-surface': '#e8e8ec',
          },
        },
        claudedark: {
          dark: true,
          colors: {
            background: '#1a1a1a',
            surface: '#252525',
            'surface-variant': '#303030',
            'surface-bright': '#2a2a2a',
            primary: '#c96a2f',
            'primary-darken-1': '#a84f20',
            secondary: '#8a7a70',
            error: '#d05050',
            success: '#5a9060',
            warning: '#d09040',
            info: '#5080c0',
            'on-background': '#e8e0d8',
            'on-surface': '#e8e0d8',
          },
        },
        liquidray: {
          dark: true,
          colors: {
            background: '#1a1d1e',
            surface: '#252829',
            'surface-variant': '#303537',
            'surface-bright': '#2a2d2f',
            primary: '#c0c0c0',
            'primary-darken-1': '#9a9a9a',
            secondary: '#607885',
            error: '#e06060',
            success: '#60aa70',
            warning: '#c09040',
            info: '#6090c0',
            'on-background': '#dde4e8',
            'on-surface': '#dde4e8',
          },
        },
        matrix: {
          dark: true,
          colors: {
            background: '#0d1117',
            surface: '#161b22',
            'surface-variant': '#21262d',
            'surface-bright': '#1a2028',
            primary: '#00d26a',
            'primary-darken-1': '#00a854',
            secondary: '#39d353',
            error: '#e05252',
            success: '#00d26a',
            warning: '#e3b341',
            info: '#79c0ff',
            'on-background': '#c9d1d9',
            'on-surface': '#c9d1d9',
          },
        },
        roblox: {
          dark: true,
          colors: {
            background: '#1a1a1a',
            surface: '#252525',
            'surface-variant': '#303030',
            'surface-bright': '#272727',
            primary: '#0066bf',
            'primary-darken-1': '#0050a0',
            secondary: '#00a2ff',
            error: '#e05252',
            success: '#52c05a',
            warning: '#e09030',
            info: '#00a2ff',
            'on-background': '#e0e0e0',
            'on-surface': '#e0e0e0',
          },
        },
        zoro: {
          dark: true,
          colors: {
            background: '#0a120a',
            surface: '#0f1d0f',
            'surface-variant': '#182818',
            'surface-bright': '#132013',
            primary: '#4caf50',
            'primary-darken-1': '#388e3c',
            secondary: '#8bc34a',
            error: '#e05252',
            success: '#66bb6a',
            warning: '#ffb300',
            info: '#29b6f6',
            'on-background': '#c8e6c9',
            'on-surface': '#c8e6c9',
          },
        },
        polarblack: {
          dark: true,
          colors: {
            background: '#1b1e21',
            surface: '#24282b',
            'surface-variant': '#2e3236',
            'surface-bright': '#272b2e',
            primary: '#e0e0e0',
            'primary-darken-1': '#bdbdbd',
            secondary: '#808080',
            error: '#e05252',
            success: '#60a060',
            warning: '#c09040',
            info: '#6090c0',
            'on-background': '#e8eaed',
            'on-surface': '#e8eaed',
          },
        },
      },
    },
    defaults: {
      VCard: { rounded: 'lg' },
      VBtn: { rounded: 'md' },
      VTextField: { variant: 'outlined', density: 'compact', hideDetails: 'auto' },
      VSelect: { variant: 'outlined', density: 'compact', hideDetails: 'auto' },
      VAutocomplete: { variant: 'outlined', density: 'compact', hideDetails: 'auto' },
      VSwitch: { density: 'compact', hideDetails: true, color: 'primary' },
      VCheckbox: { density: 'compact', hideDetails: true, color: 'primary' },
      VSlider: { color: 'primary', hideDetails: true },
      VTooltip: { contentClass: 'tooltip-readable' },
    },
  })

  nuxtApp.vueApp.use(vuetify)
})
